### ISSUE TITLE
When forwarding a message the email address is lost

### ISSUE THREAD

**Issue by cord** [QualityUnit/la-public#23]
When forwarding a message the email address of the request is lost - only the name is inserted into the header of the forwarded message:

---------- Forwarded message ----------
From: Requester Name 
Date: 01/29/2015 13:51:30
Subject: a subject

a solution could be:

---------- Forwarded message ----------
From: Requester Name <email@gmail.com>

**Comment by opok** [comment]
If this is still a problem, could you please tell us more details: version of LiveAgent, and especially your Forward message template ? Maybe you're just using an incorrect template variable. It should be like
```smarty
##---------- Forwarded message ----------##
##From:## {$from}
##Date:## {$sentDate}
##Subject:## {$subject}

{$originalMessage}
```

**Comment by cord** [comment]
the issue still exits in 4.18.5.10

when switching the forward template to html the forwarded messages are also in html format.

In html format the {$from} tag only returns the sender name, but not the sender email.

therefor the email address is no longer visible for the recipient of the forwarded message

**Comment by vzeman** [comment]
fixed in our development release - will be fixed in new release

**Comment by opok** [comment]
@cord sorry, the fix didn't make it to the current major release 4.19.0.8 but it will be in the next minor release.
