### ISSUE TITLE
Defined filter ordering resets random when moving items

### ISSUE THREAD

**Issue by triplonetienne** [QualityUnit/la-public#25]
This occurs random when:
- Save a new filter
- Move the filter up (more then 2 items)
- Modify the item, or any other item
- The new item is reset back to the bottom of the list (or the original position)

**Comment by dmilonova** [comment]
Thank you for reporting issue. It will be fixed in next release of LiveAgent

**Comment by jperdochqu** [comment]
It should be fixed.
