### ISSUE TITLE
Cannot edit "from name" for ticket resolved template

### ISSUE THREAD

**Issue by AbuJunayd** [QualityUnit/la-public#29]
When a notification for a resolved ticket is sent to the customer, the name that the customer sees in the "From" column is the login name of the mail account, as you can see in the 2 following screenshots:

What the customer sees -> http://i.imgur.com/8QRe0fb.png
Login username of mail account -> http://i.imgur.com/8rFwXT2.png

I tried to see if we could change this in the email customer templates, but we can't.

We can actually edit it for some templates, like the "ticket reply" template as you can see in this screenshot:

http://i.imgur.com/WQ34gaj.png

But there is no such setting for the "ticket resolved" template: 

http://i.imgur.com/jvUqDkG.png

**Comment by jperdochqu** [comment]
Fixed
