### ISSUE TITLE
Error in Ticket Created rule

### ISSUE THREAD

**Issue by triplonetienne** [QualityUnit/la-public#30]
Please see the attached screenshot. The purpose of the rule is to automatically assign a new outbound ticket to the creator of the ticket.
The rule works fine for a few hours, but I think the error is created when a new ticket arrives while the agent is nog logged in.
![screen shot 2016-05-19 at 13 13](https://cloud.githubusercontent.com/assets/3368251/15391856/e6ea6d20-1dc3-11e6-90eb-c4dd950d02ec.png)

**Comment by vzeman** [comment]
problem was fixed already in another internal issue
