### ISSUE TITLE
Date picker for Postpone option requires doubleclick, dismissed by single click

### ISSUE THREAD

**Issue by the-daniel-rothig** [QualityUnit/la-public#32]
Observed in Firefox 49.0.1

To reproduce:
1. Navigate to a ticket
2. Choose More -> Postpone
3. Click the "Postpone until:" box to invoke the date picker
4. Single click a target date.

Actual result: 
The date picker is dismissed without setting the contents of the text box, and validation on the text box fails

Expected result: 
The date picker is dismissed, setting the contents of the text box to the chosen date

Observation:
A doubleclick completed before the date picker disappears produces the "Expected result"

**Comment by jperdochqu** [comment]
Fixed
