### ISSUE TITLE
/api/conversations response is missing the field "assignedTo"

### ISSUE THREAD

**Issue by robokaso** [QualityUnit/la-public#33]
I was expecting the summary data about a conversation would at minimum answer the question "Who was talking to whom?" but unfortunately that's not how the current `/api/conversations` endpoint is designed. Only the owner of the conversation is specified in the response while the assigned agent is not. What makes this omission even more strange is that agent is supported as an optional parameter of the api request.

The closely related `/api/conversations/[conversationid]` response includes the field `assignedTo` which I think should also be included in the `/api/conversations`
 
https://support.ladesk.com/840770-Complete-API-reference#6d1698eaa7f970beec504017ce9f8ac4

**Comment by jperdochqu** [comment]
There is already new api `/api/v3/tickets` which contains also `assignedTo`
