### ISSUE TITLE
Errors related with "fetch_mail" or " Failed to process job numer..."

### ISSUE THREAD

**Issue by lelegon** [QualityUnit/la-public#34]
I had installed a owned license of Live agent software on a dedicated server with high hardware requirements. Live agent is acctually the only one softwware running on the server.
The script have issues since the begining, I did all upgrades to differents versions, and always the issues persist.
The support team can not find a solution for me.

1. The are continuos emails lost missings that never arrived to destiny, our clients not received some emails, even some are not show in the outbox (are missing in some part of this software).
1. There are constant errors related with "fetch_mail" or " Failed to process job numer..."
1. Sometimes differents emails accounts suddenly stopped working (not send more emails), and the only solution I found was I had to remove complete mails account from live agent, and reinstalled again (on live agent software). I dont know what happend at that sofware level, but the accounts emails start work again when you reinstalled, and a few days later start the same issues again and again.

Anyway, I have all g-suite (gmails accounts, paid service) with no problem of numbers of connections imap, pop, ..., and always turn on the "less secure aplicactions" access on gmail configuration.

My server is checked, max exuction time, all reruiqrements ok, dns, connections... all.

For example, one of my email accounts stop to work yesterday, and the team who use this account have to start using their personal emails.

I Contact support, and they are extremilly slow. I think is big issue. And I am not happy with this software because I spent too much money on licenses and time training persons to use it.
Sorry for y english.

Here paste the persistent issues log examples:
![errors](https://user-images.githubusercontent.com/33557919/32678409-fd75482c-c640-11e7-99a9-4cb3dce1c484.png)

**Comment by lelegon** [comment]
![errors2](https://user-images.githubusercontent.com/33557919/32678482-4987df18-c641-11e7-81da-beb0898ac3b2.png)

**Comment by opok** [comment]
Problems have been solved and answered in ticket GPE-JFDGB-821
