### ISSUE TITLE
User does not get password reset mail

### ISSUE THREAD

**Issue by DoogeJ** [QualityUnit/la-public#35]
One of our custommers can't get a password reset mail out of LiveAgent.

I tested this myself using incognito mode:
"If your email xxx@x-y.nl exists in our database, you will receive a reset link."

The message never shows up in the Mail outbox, nor in our outgoing mail server.

I've compared the user profile to other users, and the only difference that I can spot with earlier successful password reset mails is that the TLD contains a hyphen (-). I can't imagine that being an issue, but if it is, it is potentially a bug.

**Comment by opok** [comment]
also reported by email = ticket LRT-VEIQH-762

**Comment by msvitek** [comment]
Unable to replicate on any other installation/account and no access to customer's installation to investigate directly
